{application,unicode_set,
             [{applications,[kernel,stdlib,elixir,logger,unicode]},
              {description,"Implementation of Unicode Sets and Regexes for Elixir that can be used in\nfunction guards, compiled patterns, nimble_parsec combinators\nand regexes.\n"},
              {modules,['Elixir.Inspect.Unicode.Set',
                        'Elixir.String.Chars.Unicode.Set',
                        'Elixir.Unicode.Regex','Elixir.Unicode.Regex.Match',
                        'Elixir.Unicode.Set','Elixir.Unicode.Set.Operation',
                        'Elixir.Unicode.Set.ParseError',
                        'Elixir.Unicode.Set.Parser',
                        'Elixir.Unicode.Set.Property',
                        'Elixir.Unicode.Set.Search',
                        'Elixir.Unicode.Set.Sigil',
                        'Elixir.Unicode.Set.Transform']},
              {registered,[]},
              {vsn,"1.1.0"}]}.
